### ISSUE TITLE
Out of Memory Error

### ISSUE THREAD

**Issue by Lonemind** [DrasticDemise/Hubris#1]
I updated the server on which I am an admin from 1.3.1 to 1.4.1. Now, whenever I walk more than 5 chunks from where I start I receive a "Minecraft Has Run Out of Memory" error. No other players have this issue. I have googled this problem through and through. I have moved my allotment of memory to Minecraft up and down. I have messed with the amount of permgen it uses. I have added java arguments from this website to it. I have used both the FTB Launcher and MultiMC. I do not receive this problem on single player or any other Hubris server. I have spoken to the server owner and we have both brainstormed and fiddled with settings on the server but all to no avail.
I realize the immediate response to this is to say, "Your computer doesn't have enough RAM." This problem started when I only had 4gb of RAM. In an attempt to fix it I upgraded to 12gb of RAM. This also did not work.
Is there possibly any insight you or anyone else might give me? I'm out of ideas.

My Computer Specs
Processor   Intel(R) Core(TM) i5 CPU 750 @ 2.67GHz
Manufacturer    Intel
Speed   2.7 GHz
Number of Cores 4
Video Card  NVIDIA GeForce GTX 260
Manufacturer    NVIDIA
Chipset GeForce GTX 260
Dedicated Memory    896 MB
Total Memory    4.0 GB
Memory  13 GB
Operating System    Microsoft Windows 7 Home Premium Edition Service Pack 1 (build 7601), 64-bit
Service Pack    1
Size    64 Bit
Edition Home Premium
Display Maximum Resolution  1920 x 1080
DVD Optiarc DVD RW AD-7240S ATA Device
CD  Optiarc DVD RW AD-7240S ATA Device
Drive  
Size    931.4 GB
Free    708.9 GB

I have posted on the FTB Tech Help forums as well. So far no fruits have been born.
http://forum.feed-the-beast.com/threads/my-memory-just-isnt-what-it-used-to-be.96230/#post-1283797

**Comment by Lonemind** [comment]
Since it does not crash me I cannot attach a crash report. However here is a snippet of the console log with the information that is generated upon getting the memory error.
http://pastebin.com/JSdMgDK6

**Comment by DrasticDemise** [comment]
This unfortunately doesn't seem to be connected to the pack itself but rather your connection and the server. If you can play on any other server just fine and in single player, that is an issue with the server owner and yourself. 

However, there are a few things you can try. Attempt to stick all of your stuff into a chest and have the server owner delete your player data folder. The closest that I can reasonably suspect is that you have an item that is messing you up by causing a client memory leak. Also try to unload the chunks that you are in to see if it is something around you.

**Comment by DrasticDemise** [comment]
Ticket expired.

**Comment by Time6628** [comment]
I get this same error/problem. The server kicks you and then when you re-join the server signs are invisible are the main graphical glitches I can see.
