### ISSUE TITLE
Vinteum Dust taking over

### ISSUE THREAD

**Issue by Espergium** [DrasticDemise/Hubris#10]
Vinteum dust appears to have hijacked all AM2 ore smelting recipes. Regardless of what you have, you'll smelt it into dust instead of the intended nugget. Gamebreaking, as you currently can not get blue topaz at all in 1.5.1.

**Comment by DrasticDemise** [comment]
Are you breaking it with silk touch and then smelting it? I am pretty sure it drops directly from the ore.

**Comment by Espergium** [comment]
It is from the quest reward, which used to smelt into the gem.
Interestingly all the other ores smelt directly into the dust

**Comment by DrasticDemise** [comment]
Don't smelt topaz ore. Break it with a non-silk touch pick.
