### ISSUE TITLE
Artifacts and Infernal Mobs interaction crash

### ISSUE THREAD

**Issue by Divineaspect** [DrasticDemise/Hubris#11]
http://pastebin.com/NvvpmyJz

Infernal Mobs with Artifacts is less then awesome.

**Comment by DrasticDemise** [comment]
Can't reproduce/no similar reports.

**Comment by Divineaspect** [comment]
I've narrowed it down.
artifacts with effects on drop when striking sticky infernals
and strange projectiles from artifacts when striking a creature with BOTH poisonous and ninja.
