### ISSUE TITLE
Agricraft crash + Non-tainted lands!

### ISSUE THREAD

**Issue by astralstriker** [DrasticDemise/Hubris#13]
1.Planting seeds(any) on crops causes CTD sometimes.
2. Potato + Pumpkin = Beans (Agricraft) recipe is not working.
3. River, Eerie and Magical Forest biomes are not tainted.

**Comment by astralstriker** [comment]
Not really sure about thaumcraft biomes but isn't the river biome supposed to be tainted?

**Comment by DrasticDemise** [comment]
CTD? Crash to desktop? It is running an old version of agricraft but this crash most often occurs if you are using some kind of tick accelerator/growth on the crops at the time.

**Comment by astralstriker** [comment]
I had Agricarnation(botania) setup nearby but it was not working either.. and what about the untainted biomes?

**Comment by DrasticDemise** [comment]
Magical forest biomes should only be spawning from a pure node, eerie biomes are untaintable and necessary for thaumcraft and river/beach biomes are vanilla and vanilla hates me.
