### ISSUE TITLE
Gravestone not generating

### ISSUE THREAD

**Issue by extinak** [DrasticDemise/Hubris#16]
Around 3 times I've had a gravestone not generate at all. I don't know if this is an issue with this modpack, or with the gravestone mod. I confirmed it with the fml log. Here are the lines around my last death:

[20:51:50] [Client thread/INFO] [inventorytweaks/]: net.minecraft.client.gui.GuiGameOver
[20:51:51] [Client thread/INFO] [journeymap/]: Excalibur101 died at x:-1795, y:66, z:707. Deathpoint created: true
[20:51:52] [Server thread/DEBUG] [NotEnoughItems/]: Sending serverside check to: Excalibur101

There is no message about a grave, and no grave in the vicinity of when I died. I believe I died when taking a fall with low health. This does seem to only happen with weird deaths. I died a ton of times to mobs and I don't believe this happened then.

**Comment by DrasticDemise** [comment]
I have found that they have a habit of spawning below ground, but I have had reports of it not working before. I will see if I can find anything to fix it, but this issue has persisted for a very long time.

**Comment by Time6628** [comment]
Could it be they don't spawn if you kill yourself?

**Comment by DrasticDemise** [comment]
Known issue, no current known way to resolve it.
