### ISSUE TITLE
1.5.1 CTD

### ISSUE THREAD

**Issue by ArcticHowler** [DrasticDemise/Hubris#18]
Just updated to 1.5.1 I found one of those little dock/houseboat things, forget the mod that added it, when I went into one of the rooms on it, as I moused over one of the chests I CTD'd. Not sure if it was the contents not wanting to be displayed from outside of the chest UI, so figured I'd just post this.

Pastebin: http://pastebin.com/pHRXS971

**Comment by DrasticDemise** [comment]
The one with the pumpkins and chests? Those should have been removed :(

**Comment by ArcticHowler** [comment]
correct, and didn't know they were removed, went to it hopeful to have a safe haven until the pure nodes generated a magical forest xD

**Comment by ArcticHowler** [comment]
While I have your attention, would I suggest looking into halting pure node spawn on world gen so that they only occur via silverwood trees somehow? (Honestly I'm not even sure if that's a realistic option either way given that last I looked mana beans are a world gen only and can't randomly appear, which they are highly useful for even using thaumcraft, which actually brings up another interesting thing... why have thaumatic tinker and not tinker's construct?)

**Comment by Espergium** [comment]
Mana beans can generate on trees in a magical forest biome. If pure nodes were removed it would make the overworld a lot less pleasant and harder for thaumcraft--and natural pures are kind of necessary.
