### ISSUE TITLE
Questbook Relics of old:

### ISSUE THREAD

**Issue by dead-stroke** [DrasticDemise/Hubris#19]
Not accepting the items after being crafted.  (can also reach me on DeVco's Slack @dead_)

![screenshot_12](https://cloud.githubusercontent.com/assets/13815093/9291602/f6aac058-437f-11e5-8ee1-7075c7006375.png)

**Comment by dead-stroke** [comment]
thank you***

**Comment by VastrixL** [comment]
While I was doing this quest me and my friend had the same issue, we tried throwing them on the ground and picking them back up and that seemed to cause it to recognize them, maybe try that? If not then I'm not sure what to say.

**Comment by avatarscion** [comment]
I also have this problem, but throwing and picking them up didn't work.

**Comment by ArcticHowler** [comment]
I would say it's possible that it's an item code issue, but given that it's craft and I only know of one recipe, I'm not certain... have you tried binding them to see if that works?

**Comment by DrasticDemise** [comment]
Fixed next update.
