### ISSUE TITLE
Invisible infernal mobs

### ISSUE THREAD

**Issue by CommonExplosion** [DrasticDemise/Hubris#2]
Sometimes when a player encounters an infernal mob they become invisible to that player. It does however still attack the player. 

When this happens others can still see the mob. If we move far away from said mob it sometimes reappears (to become invisible again when approaching it).
I tested it in singleplayer and noticed the same behavior. Attacking other mobs with an AoE sword (awakened ichor sword) made damage numbers appear on the place where the mob was.

**Comment by DrasticDemise** [comment]
Infernal mobs occasionally have a modifier where they can cloak or teleport while visible behind the player. Do you experience this with any mods without the "Ninja" or "cloaking" modifier?

**Comment by CommonExplosion** [comment]
When an infernal mob has such modifiers they have some parts visible from what I've seen. When a spider has the "ninja" or "cloaking" you can still see the red eyes.
This other effect (when they completely dissapear) happens to all types of infernal mobs. Lastly, the mobs with "cloaking",... have a health bar on the top of the screen and the "bugged" ones don't.
