### ISSUE TITLE
Chop Golems placing trees in sky

### ISSUE THREAD

**Issue by extinak** [DrasticDemise/Hubris#21]
I have no idea if this is related to something in the modpack, or it's just a thaumcraft issue, but I can't find anything about it. I have a golem that chops down trees. Sometimes when he chops, a tree block appears near it. They are being places mostly in the air, but several blocks away from where the trees can reach. It's pretty annoying.

**Comment by DrasticDemise** [comment]
This isn't something I can really fix and is probably just a strange mod interaction. Sorry!
