### ISSUE TITLE
smelt issues

### ISSUE THREAD

**Issue by ludovic45110** [DrasticDemise/Hubris#22]
We are all actually on a server and there is a big problem sand, cobble, and netherquartz don't want to cook in any "machine" like the calefactor, vanilla furnace or the blast furnace. And when i put my mouse over one of those machine to see if it's cook there is a 0 below the cooked item. And when i grab it and right click it, it disappear. Please help us

**Comment by DrasticDemise** [comment]
Can you reproduce it in a single player world? Is the server on cauldron?

**Comment by ludovic45110** [comment]
i actually try all the machines and it work correctly in singleplayer but for the server i don't know i'm playing on the kookykraftmc ftb hubris server
