### ISSUE TITLE
[AM2] Dupe crafting with filled buckets using magician's workbench

### ISSUE THREAD

**Issue by Not-February** [DrasticDemise/Hubris#25]
Using version 1.5.1 of the pack from the FTB launcher on a private server.

Basically, attempting to craft anything using the magician's workbench(it is not upgraded in any way) that involves filled buckets of some kind will give you back the empty buckets without actually getting rid of the filled ones that are still left on the crafting grid.

I don't know if this is a bug within AM2 itself or not and therefore something you can't fix, but it can be pretty game-breaking(especially in regards to milk and lava, and endless buckets), so I thought I should bring it up.

**Comment by DrasticDemise** [comment]
AM2 bug, not much I can do :(

**Comment by bookerthegeek** [comment]
@DrasticDemise if you would like, and can point me to the correct page for mod tweaker, I'll makeep you some minetweaker scripts that will fix that for you.
