### ISSUE TITLE
[HQM] Crafting Recall Stones doesn't complete quest.

### ISSUE THREAD

**Issue by ArchieMagi** [DrasticDemise/Hubris#27]
Hello!

I haven't seen if this is a problem for anyone else but I've tried completing the quest which is completed after crafting a Recall stone and an Interdimensional Recall stone, but after crafting two times, it doesn't detect the stones. Anyone else getting this? Am I just missing something?

**Comment by VxeR** [comment]
I am having the same problem. I read that someone fixed it with droping and picking them up again - did not work for me.

What I've tried and did not work:
1) craft new ones, bind and name them (eg. "Home")
2) droping and picking them up again
3) use them 5 times and refill with ender pearl
4) name them exactly as in the quest book (italic name)
5) leave empty name (names them exactly as in the quest book - non-italic)
6) cheat them in
7) most of all posible combinations of the above

**Comment by DrasticDemise** [comment]
Fixed next update.
