### ISSUE TITLE
Artifacts & Protections

### ISSUE THREAD

**Issue by bookerthegeek** [DrasticDemise/Hubris#29]
Hello!

Just wanted to let you know that in both a server and single player enviroment, artifacts with exploding or exploding arrow attributes will bypass protections.

This was tested servers idea with grief prevention and Forge tested with MyTown2.

Latest version of the pack and applicable supporting mods / plugins.

**Comment by Draco18s** [comment]
Given how the explosive component uses the exact same function calls as TNT and Creepers, I'm not sure how this is true unless the protection system coremods TNT and Creepers specifically, rather than the world.newExplosion(...) method.

**Comment by bookerthegeek** [comment]
Look into that I will.
