### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by specialmaster** [DrasticDemise/Hubris#3]
When i go to the nether,game crashes, tried to go through it the game crashes and I have to restart.This problem appeared recently

**Comment by Slind14** [comment]
please put the crash-report on gist.github.com and post the link here

**Comment by specialmaster** [comment]
https://gist.github.com/specialmaster/858abf3d4109e9aed29b/download#file-gistfile1-txt

**Comment by specialmaster** [comment]
Try to update to 1.4.2-problem is still here
https://gist.github.com/specialmaster/c660c597b0018d20be9a#file-gistfile1-txt

**Comment by specialmaster** [comment]
Here is the working save:<a href=http://www.filedropper.com/-_8><img src=http://www.filedropper.com/download_button.png width=127 height=145 border=0/></a><br /><div style=font-size:9px;font-family:Arial, Helvetica, sans-serif;width:127px;font-color:#44a854;> <a href=http://www.filedropper.com >file upload</a></div>

**Comment by DrasticDemise** [comment]
Simply copy and paste the text into a paste bin or something, don't need the download file. Also if the crash says Ticking Entity Error, this can be solved by going into the forge.cfg and enabling the removal of erroring tile entities. It may be a crash caused by nether ores.

**Comment by specialmaster** [comment]
Enabling the removal of erroring entities and  tile entities doesnt
 help me.game still  crashes

**Comment by specialmaster** [comment]
adviсes?
