### ISSUE TITLE
Blocks change on update.

### ISSUE THREAD

**Issue by Teryn180** [DrasticDemise/Hubris#8]
On updating a small private server from 1.4.1 to 1.5.0, a large number of blocks in the world changed what they are. Notably Chisel 2 blocks, though some vanilla blocks appear to have been affected too.

**Comment by Teryn180** [comment]
Doing some more looking, I was wrong, vanilla is unchanged, and Thaumcraft4 blocks seem to be unchanged. Ars Magica, Witchery, Iron Chests, all the thaumcraft addons and botania all hand their blocks exchanged, mostly with other mods.

**Comment by yarma92** [comment]
This is due to some mod updates and new mods being added and some being removed. This causes a cascade of item ID changes. Resulting in blocks changing to what ever the previous ID no represents. Not a bug, just a side effect of extensive updates that can't be avoided.

**Comment by Teryn180** [comment]
I was kind of afraid of that. Is there any easy way to fix it? Or would I have to go though and check everything by hand?

**Comment by yarma92** [comment]
You would need to replace it all by hand as far as I'm aware also there is some new or in the world gen now I believe. But don't quote me on that. I think it's shadow ore.

On 6 Aug 2015 20:45, Teryn180 notifications@github.com wrote:
I was kind of afraid of that. Is there any easy way to fix it? Or would I have to go though and check everything by hand?

---

**Comment by DrasticDemise** [comment]
Not really something I can do anything about now, I will look to see if anyone else is having this issue.
