### ISSUE TITLE
Dimensional Stones Unbindable

### ISSUE THREAD

**Issue by Espergium** [DrasticDemise/Hubris#9]
The dimensional stones can no longer be bound as they return the error "Stone is still charging".
Notably, their icons went from the generic soft stone to the red etched stone. 1.5.0 and 1.5.1

**Comment by yarma92** [comment]
I can confirm this is also happening with standard recall stones including the two rewarded from the quest 'Defense' which should also by 'Defence' but minor issue. Also related to this is if you attempt to bind recall stones that are in a stack a stone will vanish. Nothing about either of these issues on the Recall Stones repo.

Edit: I have tried adjusting the configs so none of the recall stones have a cooldown and it has not fixed the issue.

**Comment by Patzos** [comment]
I can add that in version 1.5.0 (I always stay a version behind) recall stones found in dungeon loot were the wrong type ones. When you craft them they are grey without the red markings, they get them when bound. The rewarded ones are already "red". Seems like an ID or meta data issue.

**Comment by DrasticDemise** [comment]
This is fixed next update.
